name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          keep-state: true

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v4

      - name: Build Docker image via make build-image
        run: |
          make build-image


      - name: Verify Docker image
        run: |
          docker images holon-coherence
          docker inspect holon-coherence:latest >/dev/null
