name: Test - Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Docker cannot run on macos-latest runners (see .github/macos-docker.md)
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Cache conda packages
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: ${{ runner.os }}-conda-

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml
          channels: conda-forge
          auto-activate-base: false
          activate-environment: holon
          conda-remove-defaults: true
          use-only-tar-bz2: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          keep-state: true

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v4

      - name: Build Docker image via make build-image
        run: |
          make build-image


      - name: Run integration tests
        shell: bash -el {0}
        run: uv sync; uv run task test-docker
